name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write        # allow publishing
  id-token: write     # allow OIDC token exchange

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - uses: actions/checkout@v3

      # 1) configure the Pages environment (sets up OIDC, protection rules, etc.)
      - uses: actions/configure-pages@v3

      # 2) build your site however you normally would
      - name: Install & build
        run: |
          npm install --legacy-peer-deps
          npm run build

      # 3) package & upload the output
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      # 4) deploy the artifact to Pages
      - uses: actions/deploy-pages@v1