name: CI & Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install & Build at dynamic path
        run: |
          pkg_dir=$(dirname "$(find . -type f -name package.json | head -n1)")
          echo "Found package.json in: $pkg_dir"
          npm install --legacy-peer-deps --prefix "$pkg_dir"
          npm run build --prefix "$pkg_dir"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./munjero/dist"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2